title: lausek
author: lausek
description: "This is my little blog about programming - mainly in ABAP - and other computer stuff."
keywords: "lausek, sap, abap, laurin, kirbach, lpk"

tags_dir: tagged
tags:
    - abap
    - sap
    - fun
    - hardware

collections:
    extra:
        output: true

highlighter: rouge
sass:
    style: compressed
